backend:
  name: github
  repo: piotrovskyi/open-austin-website-demo

media_folder: public/media
public_folder: /media

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: public/media
    public_folder: /media
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "thumb",
          widget: "image",
          required: true,
        }
      - {
          label: "Featured Image alt",
          name: "thumbalt",
          widget: "string",
          required: true,
        }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          required: true,
        }
      - { label: "Tags", name: "tags", widget: "list", required: true }
      - { label: "Summary", name: "summary", widget: "string", required: true }
      - {
          label: "Author",
          name: "author",
          widget: "object",
          required: true,
          fields:
            [
              {
                name: "first_name",
                label: "First Name",
                widget: "string",
                required: true,
              },
              {
                name: "last_name",
                label: "Last Name",
                widget: "string",
                required: true,
              },
              {
                name: "email",
                label: "Email",
                widget: "string",
                required: true,
              },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - label: "Projects"
    name: "projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    media_folder: public/projects_media
    public_folder: /projects_media
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - { label: "Type", name: "type", widget: "string", required: true }
      - { label: "Status", name: "Status", widget: "string", required: true }
      - {
          label: "Access at",
          name: "access_at",
          widget: "string",
          required: true,
        }
      - {
          label: "Project at",
          name: "project_at",
          widget: "string",
          required: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "screenshot",
          widget: "image",
          required: true,
        }

      - {
          label: "Archived",
          name: "archived",
          widget: "boolean",
          required: true,
        }
      - {
          label: "Categories",
          name: "Categories",
          widget: "list",
          required: true,
        }
      - { label: "Contact", name: "Contact", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - label: "Pages"
    name: "pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    media_folder: public/media
    public_folder: /media
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }

      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
